<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="48482" started-at="2020-12-30T19:18:21 IST" finished-at="2020-12-30T19:19:09 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="48482" started-at="2020-12-30T19:18:21 IST" finished-at="2020-12-30T19:19:09 IST">
      <class name="Scripts.WeatherReportingComparator">
        <test-method status="PASS" signature="initialize(java.lang.String)[pri:0, instance:Scripts.WeatherReportingComparator@6b67034]" name="initialize" is-config="true" duration-ms="38543" started-at="2020-12-30T19:18:21 IST" finished-at="2020-12-30T19:18:59 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="verifyWeatherReportingComparator()[pri:0, instance:Scripts.WeatherReportingComparator@6b67034]" name="verifyWeatherReportingComparator" duration-ms="9050" started-at="2020-12-30T19:18:59 IST" finished-at="2020-12-30T19:19:08 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Variance is greater than 2]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Variance is greater than 2
at org.testng.Assert.fail(Assert.java:97)
at Scripts.WeatherReportingComparator.verifyWeatherReportingComparator(WeatherReportingComparator.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyWeatherReportingComparator -->
        <test-method status="PASS" signature="closeConnection()[pri:0, instance:Scripts.WeatherReportingComparator@6b67034]" name="closeConnection" is-config="true" duration-ms="1424" started-at="2020-12-30T19:19:11 IST" finished-at="2020-12-30T19:19:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeConnection -->
      </class> <!-- Scripts.WeatherReportingComparator -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
